### ISSUE TITLE
Gorilla Player and Shared Asset Projects

### ISSUE THREAD

**Issue by djshaw01** [UXDivers/Gorilla-Player-Support-And-Issues#13]
Gorilla seems to have issues following xaml files in Xamarin Forms Shared Asset projects.
This is on the Mac Version.  I cannot find the relevant logs to get the errors (please let me know where to find them, and I will attach), but I confirmed by adding a new PCL project to my solution and copied the xaml contents to this new project, and the display works flawlessly.  I'm unsure if there is currently another way around this.

This is a great project by the way.  thank you for allowing me to join in the beta.

Cheers.
  Daniel

**Comment by jpbrocca** [comment]
Hi Daniel, thanks for your comments!

You can find the logs in this folder:

C:\users\<YOU>\.gorilla\logs

Also if you could upload a sample project showing the issue that could be a bug help too!

Regards and again thank you,
JP

**Comment by Korayem** [comment]
I confirm exact same problem here on OSX

I simply created a new Xamarin Forms Solution using Shared Asset Project and added a single XAML as follows
```
<?xml version="1.0" encoding="UTF-8"?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms" xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" x:Class="PortawyMobile.MainScreen">
	<ContentPage.Content>
		<Label Text="Hey!" />
	</ContentPage.Content>
</ContentPage>
```

From the logs ``
```
{"level":"info","message":"Setting Target: Views\\MainScreen.xaml (85DF24C8-4334-48CE-80AB-F9ECC53C6322)","timestamp":"2016-01-14T07:43:18.351Z"}
{"level":"info","message":"Solution not found","timestamp":"2016-01-14T07:43:18.352Z"}
{"level":"info","message":"Adding solution: /path/to/solution/projects/TestGorillaPlayer.sln","timestamp":"2016-01-14T07:43:18.353Z"}

```

**Comment by jpbrocca** [comment]
Hi Korayem, thanks for taking the time to explain the issue.
Currently only PCL projects are supported, that is why when you add everything to the PCL everything works.

**Comment by Korayem** [comment]
Awesome! thanks for the clarification

**Comment by jpbrocca** [comment]
Adding the Feature Request label.
Here is a use case suggested by a user:

https://github.com/xamarin/Sport

**Comment by Horrorshow** [comment]
Hey, i gave up  using gorilla player for the moment due to this issue, as if you need several libs not ported for PCL you either have to make a choice, writing without xaml and use sharedlib+whatever nuget lib u want. Or find a PCL port for the lib like (restsharp acr.userdialogs++) so you can use xaml+gorilla player. Hope you fix this issue as this is a great project ! I might have missed out something though!

**Comment by jpbrocca** [comment]
Hi @Horrorshow,
we are currently working on adding support for shared projects since this feature is being highly requested :)

So if you could wait a few days more you will be able to give it a try :)

Best,
JP

**Comment by Horrorshow** [comment]
Sounds good!,
Might not be the right place but i got some other stuff as well if you like:
1) Some stability improvement on the server, i have to restart it sometimes due to me using several VS2015+. (Maybe sockets died?) So it never needs to be restarted.

2) If its possible to really deploy the gorillaplayer without force uninstalling on the devices when switching from mac/win.

3) Vs2015 better menu for gorillla player like stick to xml onto the solution explorer.

4) Often the gorilla player needs to be recompiled and relaunched as it just shuts down (i havent checked log on android why)

**Comment by jpbrocca** [comment]
Hi @Horrorshow and yes, I am very interested in that other stuff you mentioned :)

I have added #41 for you.
Could you add those comments there and add more context/ellaborate more if possible ?

If you attach your logs (remember to zip them to able to add them here) that will be of great help.

Thank you very much for helping us!

**Comment by LeoHere** [comment]
Hi all, v0.8.3 add support for shared projects.
