### ISSUE TITLE
Could not initiate Gorilla

### ISSUE THREAD

**Issue by takigava** [UXDivers/Gorilla-Player-Support-And-Issues#24]
Could not initiate Gorilla, port 8080 in use.

I have local iis running.

How i can change port number for gorilla?

**Comment by jpbrocca** [comment]
Hi,

By default Gorilla should accept connections from any ip address. Currently we only suppor changing the port. We don't support binding to a specific IP (we will if needed). Gorilla by default uses ports 8080 and 14578. The latter is for server node discovery, using UDP. 

The easyest way to change the port is to edit:

*c:\Users\<you>\.gorilla\config.json.*

By default this file has something like:

~~~
{"serverName":"Gorilla on Computer Name"}
~~~

This serverName is just a friendly name for your Gorilla server, it is not related to network stuff. In order to change the port you should add a port as follows:

~~~
{"serverName":"Gorilla on Computer Name", "port":8080}
~~~

If you want to change the discovery port too you should use 

~~~
{"serverName":"Gorilla on Computer Name", "port":8081, "discoveryPort":14579}
~~~

Once you change the "port" you will need to change it in your Xamarin Studio too under

~~~
Preferences > Gorilla Player > Server
~~~

If you are on Windows it could happen that the Server settings could not be displayed though. This is something we are fixing.

Let me know if that helps

**Comment by takigava** [comment]
I have changed port number and it starts. but i can't see server settings(((

**Comment by jpbrocca** [comment]
OK, yes, this is a know issue.
We have uploaded a new installer, please download it from here:
https://github.com/UXDivers/Gorilla-Player-Support-And-Issues/releases/download/v0.8.2/gorilla-player_0.8.2.exe

...it should work now.
Can you try again?

Remember to uninstall first your current version then make sure Visual Studio and Xamarin Studio are closed and then install.

Thanks!

**Comment by takigava** [comment]
Same result. Can't see server node in xamarin...
Xamarin version 5.10.1

**Comment by takigava** [comment]
Update. 
After closing of all opened programs, stopping iis,and killing some processes, it is finally started correctly. 
It remains only to find out the correct sequence and why is him blocked
