### ISSUE TITLE
[Gorilla Player 8.3.0] Error occurred while setting Gorilla Target XAML. File Demo.xaml (Can´t locate the target xaml within the project).

### ISSUE THREAD

**Issue by Korayem** [UXDivers/Gorilla-Player-Support-And-Issues#47]
Whenever I try to open any XAML from my Shared Project, I get the above error.

**Comment by jpbrocca** [comment]
Hi @Korayem, how have you been?

Are you on Visual Studio or Xamarin Studio?
Is there any chance you could share your project?
You can email me if you prefer not to leave it here for public access:

![image](https://cloud.githubusercontent.com/assets/15996999/13249955/f1e73426-da05-11e5-9b62-a01683650ba8.png)

Best,
JP

**Comment by Korayem** [comment]
It's Xamarin Studio on OSX

Here's the file
```
<?xml version="1.0" encoding="UTF-8"?>
<ContentPage Title="Login" xmlns="http://xamarin.com/schemas/2014/forms" xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" x:Class="MyProject.Login">
	<ContentPage.Content>
		<StackLayout Orientation="Vertical" VerticalOptions="CenterAndExpand">
			<StackLayout Orientation="Horizontal">
				<Label Text="Username:" VerticalOptions="Center" />
				<Entry x:Name="UsernameEntry" Placeholder="myemail@gmail.com" HorizontalOptions="CenterAndExpand" />
			</StackLayout>
			<StackLayout Orientation="Horizontal">
				<Label Text="Password:" VerticalOptions="Center" />
				<Entry x:Name="PasswordEntry" Placeholder="dummy" IsPassword="true" HorizontalOptions="CenterAndExpand" />
			</StackLayout>
			<Label x:Name="messageLabel" />
			<Button Text="Login" Clicked="OnClicked" IsEnabled="{Binding IsFormActive}" VerticalOptions="EndAndExpand" />
		</StackLayout>
	</ContentPage.Content>
</ContentPage>
```

**Comment by jpbrocca** [comment]
OK, I need the project so I can reproduce the bug :)
Only the XAML file is not enough.

Any chance you could send your project ?

Thanks!
JP

**Comment by Korayem** [comment]
Ok sure. Check your email...

:)

**Comment by jpbrocca** [comment]
Checked, thank you! :D

**Comment by LeoHere** [comment]
Hi @Korayem,

Thanks for sending the sample project.

I tested your solution and I'm able preview it. I got an error in one or two XAMLs but those do not seem to be related to shared projects. I will further investigate those later.

In order to diagnose why you are not able to preview it:

1) Restart XS

2) Please ensure that the version of your XS addin is indeed 0.8.3.0. Goto Xamarin Studio->Addin Manager, then IDE Extensions and check the version of gorilla player addin.

3) Please ensure the host app is also 0.8.3.0. Go to http://localhost:9014 (assuming you didn't set a different port)

If everything looks ok, open your solution and try to preview it again.

My guess is that something was not property installed.

Best,
Leo

**Comment by Korayem** [comment]
Awesome! It's working now.

Seems installed didnt update XS plugin or it required a restart

Thanks a bunch :)
